### ISSUE TITLE
Python Version

### ISSUE THREAD

**Issue by HildaNya** [josebeo2016/biosegment#2]
Hi! Your work is awesome. 
I'd like to try the biosegment part, but I'm having trouble setting up the environment. I saw from the ipynb file that you were using Python 3.9. But there seem to be several incompatible packages in requirements.txt. Any tips?

Thanks!

**Comment by josebeo2016** [comment]
Hello. Sorry for late reply.
I have checked my local environment and it works well with Python 3.9.18
